THREE.t=function(c,k){function f(b){if(!1!==a.enabled){b.preventDefault();var d=a.a===document?a.a.body:a.a;if(g===e.v){if(!0===a.k)return;n.set(b.clientX,b.clientY);p.i(n,q);a.q(2*Math.PI*p.x/d.clientWidth*a.l);a.F(2*Math.PI*p.y/d.clientHeight*a.l);q.c(n)}else if(g===e.r){if(!0===a.h)return;r.set(b.clientX,b.clientY);w.i(r,s);0<w.y?a.o():a.p();s.c(r)}else if(g===e.u){if(!0===a.g)return;t.set(b.clientX,b.clientY);x.i(t,u);a.e(x);u.c(t)}a.update()}}function h(){!1!==a.enabled&&(a.a.removeEventListener("mousemove",
f,!1),a.a.removeEventListener("mouseup",h,!1),g=e.NONE)}function l(b){if(!1!==a.enabled&&!0!==a.h){var d=0;b.wheelDelta?d=b.wheelDelta:b.detail&&(d=-b.detail);0<d?a.p():a.o()}}this.object=c;this.a=void 0!==k?k:document;this.enabled=!0;this.target=new THREE.f;this.h=!0;this.H=1;this.aa=0;this.Y=Infinity;this.k=!1;this.l=1;this.g=!0;this.j=7;this.S=!1;this.n=2;this.ba=Math.PI/3;this.Z=2*Math.PI/3;this.ca=-Math.PI/4;this.$=Math.PI/4;this.fa=!1;this.keys={M:37,R:38,P:39,K:40};var a=this,q=new THREE.b,
n=new THREE.b,p=new THREE.b,u=new THREE.b,t=new THREE.b,x=new THREE.b,s=new THREE.b,r=new THREE.b,w=new THREE.b,y=0,z=0,v=1,A=new THREE.f,B=new THREE.f,e={NONE:-1,v:0,r:1,u:2,B:3,w:4,A:5},g=e.NONE,C={type:"change"};this.q=function(b){void 0===b&&(b=2*Math.PI/60/60*a.n);z-=b};this.F=function(b){void 0===b&&(b=2*Math.PI/60/60*a.n);y-=b};this.C=function(a){var d=new THREE.f,c=this.object.X.elements;d.set(c[0],c[1],c[2]);d.ea(-a);A.add(d)};this.D=function(a){var d=new THREE.f,c=this.object.X.elements;
  d.set(c[4],c[5],c[6]);d.ea(a);A.add(d)};this.e=function(b){var d=a.a===document?a.a.body:a.a;if(void 0!==a.object.W){var c=a.object.position.clone().sub(a.target).length(),c=c*Math.tan(a.object.W/2*Math.PI/180);a.C(2*b.x*c/d.clientHeight);a.D(2*b.y*c/d.clientHeight)}else void 0!==a.object.top?(a.C(b.x*(a.object.right-a.object.left)/d.clientWidth),a.D(b.y*(a.object.top-a.object.bottom)/d.clientHeight)):console.warn("WARNING: OrbitControls.js encountered an unknown camera type - pan disabled.")};this.o=
  function(){var b;void 0===b&&(b=Math.pow(.95,a.H));v/=b};this.p=function(){var b;void 0===b&&(b=Math.pow(.95,a.H));v*=b};this.update=function(){var b=this.object.position,d=b.clone().sub(this.target),c=Math.atan2(d.x,d.z),e=Math.atan2(Math.sqrt(d.x*d.x+d.z*d.z),d.y);this.S&&this.q(2*Math.PI/60/60*a.n);var c=c+z,e=e+y,c=Math.max(this.ca,Math.min(this.$,c)),e=Math.max(this.ba,Math.min(this.Z,e)),e=Math.max(1E-6,Math.min(Math.PI-1E-6,e)),f=d.length()*v,f=Math.max(this.aa,Math.min(this.Y,f));this.target.add(A);
    d.x=f*Math.sin(e)*Math.sin(c);d.y=f*Math.cos(e);d.z=f*Math.sin(e)*Math.cos(c);b.c(this.target).add(d);this.object.Ca(this.target);y=z=0;v=1;A.set(0,0,0);0<B.ya(this.object.position)&&(this.dispatchEvent(C),B.c(this.object.position))};this.a.addEventListener("contextmenu",function(a){a.preventDefault()},!1);this.a.addEventListener("mousedown",function(b){if(!1!==a.enabled){b.preventDefault();if(0===b.button){if(!0===a.k)return;g=e.v;q.set(b.clientX,b.clientY)}else if(1===b.button){if(!0===a.h)return;
      g=e.r;s.set(b.clientX,b.clientY)}else if(2===b.button){if(!0===a.g)return;g=e.u;u.set(b.clientX,b.clientY)}a.a.addEventListener("mousemove",f,!1);a.a.addEventListener("mouseup",h,!1)}},!1);this.a.addEventListener("mousewheel",l,!1);this.a.addEventListener("DOMMouseScroll",l,!1);this.a.addEventListener("keydown",function(b){if(!1!==a.enabled&&!0!==a.fa&&!0!==a.g){var d=!1;switch(b.keyCode){case a.keys.R:a.e(new THREE.b(0,a.j));d=!0;break;case a.keys.K:a.e(new THREE.b(0,-a.j));d=!0;break;case a.keys.M:a.e(new THREE.b(a.j,
        0));d=!0;break;case a.keys.P:a.e(new THREE.b(-a.j,0)),d=!0}d&&a.update()}},!1);this.a.addEventListener("touchstart",function(b){if(!1!==a.enabled)switch(b.touches.length){case 1:if(!0===a.k)break;g=e.B;q.set(b.touches[0].pageX,b.touches[0].pageY);break;case 2:if(!0===a.h)break;g=e.w;var d=b.touches[0].pageX-b.touches[1].pageX;b=b.touches[0].pageY-b.touches[1].pageY;s.set(0,Math.sqrt(d*d+b*b));break;case 3:if(!0===a.g)break;g=e.A;u.set(b.touches[0].pageX,b.touches[0].pageY);break;default:g=e.NONE}},
        !1);this.a.addEventListener("touchend",function(){!1!==a.enabled&&(g=e.NONE)},!1);this.a.addEventListener("touchmove",function(b){if(!1!==a.enabled){b.preventDefault();b.stopPropagation();var d=a.a===document?a.a.body:a.a;switch(b.touches.length){case 1:if(!0===a.k)break;if(g!==e.B)break;n.set(b.touches[0].pageX,b.touches[0].pageY);p.i(n,q);a.q(2*Math.PI*p.x/d.clientWidth*a.l);a.F(2*Math.PI*p.y/d.clientHeight*a.l);q.c(n);break;case 2:if(!0===a.h)break;if(g!==e.w)break;d=b.touches[0].pageX-b.touches[1].pageX;
          b=b.touches[0].pageY-b.touches[1].pageY;r.set(0,Math.sqrt(d*d+b*b));w.i(r,s);0<w.y?a.p():a.o();s.c(r);break;case 3:if(!0===a.g)break;if(g!==e.A)break;t.set(b.touches[0].pageX,b.touches[0].pageY);x.i(t,u);a.e(x);u.c(t);break;default:g=e.NONE}}},!1)};THREE.t.prototype=Object.create(THREE.ka.prototype);(function(){window.m=window.m||{};var c=Fifteen.G=new THREE.qa,k=$("#gamespace");k.click(function(a){if(!window.frame.Ba){var c=a.pageX-k.offset().left;a=a.pageY-k.offset().top;c=new THREE.f(c/600*2-1,1-a/600*2,h.Da);c.Ha(h);c=(new THREE.pa(h.position,c.sub(h.position).normalize())).Aa(Fifteen.G.children,!0);console.log(c);0<c.length&&(iObjs=_.map(c,function(a){return a.object.parent}),window.frame.za(iObjs))}});var f=new THREE.va;f.Ea(600,600);f.Fa=!0;k.append(f.a);var h=new THREE.oa(55,1,.1,300);
          h.position.z=25;new THREE.t(h,document.getElementById("gamespace"));var l=new THREE.sa(15658734,.75);l.position.set(-8,8,40);c.add(l);l=new THREE.ja(16777215,1);l.position.set(-8,8,40);c.add(l);var a=Fifteen.ga=function(){requestAnimationFrame(a);f.ga(c,h)}})();(function(){window.m=window.m||{};var c=Fifteen.ua=function(c,f){this.frame=c;this.da=this.ha(f);0!==f&&Fifteen.G.add(this.da)};c.d=new THREE.ra;c.d.moveTo(-2,-2);c.d.lineTo(-2,2);c.d.lineTo(2,2);c.d.lineTo(2,-2);c.d.lineTo(-2,-2);c.L=new THREE.la(c.d,{wa:1,Ga:2,T:!0,V:.25,U:.15,xa:3});c.N=new THREE.O({color:1052784});c.I=new THREE.ia(4.75,4.755,.2);c.J=new THREE.O({color:12288});c.Q=new THREE.ma({color:14540253});c.prototype.ha=function(k){var f=new THREE.na,h=new THREE.s(c.L,c.N);h.position.z=-1;
            var l=new THREE.s(c.I,c.J);l.position.z=-.4;var a=new THREE.ta(k,{font:"helvetiker",size:2,height:1,T:!0,V:.25,U:.15}),a=new THREE.s(a,c.Q);a.position.set(9<k?-1.75:-.75,-1,-.5);f.add(h);f.add(a);f.add(l);f.name="Tile "+k;return f}})();
